services:
  backend:
    build: ./backend
<<<<<<< Updated upstream
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
=======
    env_file: .env
>>>>>>> Stashed changes

  frontend:
    build: ./frontend
